name: Node.js Package

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20.9
      - run: npm install
      - run: npm ci
      - run: npm publish
        env:
          NPM_CONFIG_TOKEN: ${{secrets.GITHUB_TOKEN}}
